Update README.md
IBM/argocd-vault-plugin pull request #168
Opened 2021-07-26 18:47 UTC by marcportabellaclotet-mt

### Description

Adds documentation for helm extra args use case. 
**Fixes:** [issue](https://github.com/IBM/argocd-vault-plugin/issues/166)

### Checklist
Please make sure that your PR fulfills the following requirements:
- [] Reviewed the guidelines for contributing to this repository
- [ ] The commit message follows the [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] Tests for the changes have been updated
- [ ] Docs have been added / updated

### Type of Change

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [x ] Documentation content changes
- [ ] Other (please describe)

### Other information

2021-07-27 12:35 UTC, werne2j requested changes
Thanks @marcportabellaclotet-mt! Can you format the commit message to follow the conventional commits standard? https://www.conventionalcommits.org/en/v1.0.0/#summary

2021-07-27 12:35 UTC, werne2j commented on README.md
> +...
Can you remove the ... you have inside the code block?

2021-07-28 14:32 UTC, jkayani approved these changes
LGTM, thanks a lot

2021-07-28 19:54 UTC, werne2j approved these changes

2021-07-28 19:54 UTC, merged